<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="errors" nsURI="http://anatlyzer/atl/errors" nsPrefix="atl_errors">
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1"
        eType="#//Problem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="batchAnalysis" upperBound="-1"
        eType="#//BatchAnalysis" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisInfo" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Problem" abstract="true" eSuperTypes="#//AnalysisInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependents" upperBound="-1"
        eType="#//Problem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" lowerBound="1"
        eType="#//SeverityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsCSP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//ProblemStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoredByUser" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//StringToObjectMap"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BatchAnalysis" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProblemStatus">
    <eLiterals name="STATICALLY_CONFIRMED"/>
    <eLiterals name="INITIALLY_DISCARDED" value="1"/>
    <eLiterals name="WITNESS_REQUIRED" value="2"/>
    <eLiterals name="ERROR_CONFIRMED" value="3"/>
    <eLiterals name="ERROR_CONFIRMED_SPECULATIVE" value="4"/>
    <eLiterals name="ERROR_DISCARDED" value="5"/>
    <eLiterals name="ERROR_DISCARDED_DUE_TO_METAMODEL" value="6"/>
    <eLiterals name="USE_TIME_OUT" value="7"/>
    <eLiterals name="USE_INTERNAL_ERROR" value="8"/>
    <eLiterals name="IMPL_INTERNAL_ERROR" value="9"/>
    <eLiterals name="CANNOT_DETERMINE" value="10"/>
    <eLiterals name="NOT_SUPPORTED_BY_USE" value="11"/>
    <eLiterals name="PROBLEMS_IN_PATH" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SeverityKind">
    <eLiterals name="ERROR"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="STYLE_SUGGESTION" value="3"/>
    <eLiterals name="PERFORMANCE_SUGGESTION" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recovery" abstract="true"/>
  <eSubpackages name="atl_error" nsURI="http://bento/analysis/atl/analysis/errors"
      nsPrefix="atl_error">
    <eClassifiers xsi:type="ecore:EClass" name="LocalProblem" abstract="true" eSuperTypes="#//Problem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="displayedElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="missing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recovery" eType="#//Recovery"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="klass" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuntimeError" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Warning" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="StyleHint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PerformanceHint" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclCompliance" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclComplianceProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidArgumentProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="TargetModelConformanceProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="NoBindingForCompulsoryFeature" eSuperTypes="#//atl_error/TargetModelConformanceProblem #//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="No binding for compulsory target feature"/>
        <details key="text" value="Applicable to references and string attributes without default value."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="no-binding-compulsory-feature"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subrule" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//atl_error/NoBindingForCompulsoryFeatureKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidAssignmentImperativeBinding"
        eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid assignment in imperative binding"/>
        <details key="text" value="Left and right types of a binding statement are not compatible"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="invalid-assignment-imperative-binding"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NoBindingForCompulsoryFeatureKind">
      <eLiterals name="IN_NORMAL_RULE"/>
      <eLiterals name="MISSING_SUBRULE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingPossiblyUnresolved" eSuperTypes="#//atl_error/BindingProblem #//atl_error/BindingResolution">
      <eAnnotations source="description">
        <details key="name" value="Binding possibly unresolved"/>
        <details key="text" value="A binding may be unresolved if certain conditions hold"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="always-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="unresolved-binding"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="problematicClasses" lowerBound="1"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="problematicClassesImplicit"
          lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingWithoutRule" eSuperTypes="#//atl_error/BindingProblem #//atl_error/BindingResolution">
      <eAnnotations source="description">
        <details key="name" value="No rule to resolve binding"/>
        <details key="text" value="No rule able to resolve the binding can be found"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="unresolved-binding"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingWithResolvedByIncompatibleRule"
        eSuperTypes="#//atl_error/BindingProblem #//atl_error/BindingResolution">
      <eAnnotations source="description">
        <details key="name" value="Binding resolved by rule with invalid target"/>
        <details key="text" value="A rule may resolve a binding but its first output pattern will produce a target element incompatible with the binding feature"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="sometimes-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="invalid-target"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureNotFound" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Feature not found"/>
        <details key="text" value="Feature cannot be found in an object's class"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationNotFound" eSuperTypes="#//atl_error/OperationCallInvalid #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Operation not found"/>
        <details key="text" value="Operation cannot be found in an object's class"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationFoundInSubtype" eSuperTypes="#//atl_error/OperationNotFound #//atl_error/FoundInSubtype #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Operation found in subtype"/>
        <details key="text" value="Operation cannot be found in an object's class, but found in subtype. The error may not happen depending on the program logic."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="sometimes-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="found-in-subtype"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FoundInSubtype" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="possibleClasses" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="missingClasses" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureFoundInSubtype" eSuperTypes="#//atl_error/FeatureNotFound #//atl_error/FoundInSubtype #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Feature found in subtype"/>
        <details key="text" value="Feature cannot be found in an object's class, but found in subtype. The error may not happen depending on the program logic."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="sometimes-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="found-in-subtype"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessToUndefinedValue" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Possible access to undefined feature"/>
        <details key="text" value="Source cardinality check"/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="sometimes-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="undefined-value"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessToUndefinedValue_ThroughEmptyCollection"
        eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Possible access to undefined feature via empty collection"/>
        <details key="text" value="Source cardinality check"/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="always-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="undefined-value"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuleConflicts" eSuperTypes="#//BatchAnalysis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conflicts" upperBound="-1"
          eType="#//atl_error/ConflictingRuleSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConflictingRuleSet" eSuperTypes="#//Problem">
      <eAnnotations source="description">
        <details key="name" value="Rule conflict"/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="sometimes-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="analysis (separate)"/>
        <details key="source" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
          upperBound="-1" eType="ecore:EClass types.ecore#//Metaclass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="analyserInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TargetConformanceViolations" eSuperTypes="#//BatchAnalysis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetIssues" upperBound="-1"
          eType="#//atl_error/BatchTargetConformanceIssue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BatchTargetConformanceIssue" abstract="true"
        eSuperTypes="#//Problem"/>
    <eClassifiers xsi:type="ecore:EClass" name="TargetInvariantViolation" eSuperTypes="#//atl_error/BatchTargetConformanceIssue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariantName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionOperationOverNoCollectionError"
        eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Collection operation over no collection (``$\rightarrow$'' vs. ``.'')"/>
        <details key="example" value="aClassInstance->select(...)"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-style"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureAccessInCollection" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Feature access in collection"/>
        <details key="text" value="Collections do not have features. Dot-notation cannot be used over them"/>
        <details key="example" value="Sequence { }.length"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationOverCollectionType" eSuperTypes="#//atl_error/OclComplianceProblem">
      <eAnnotations source="description">
        <details key="name" value="Operation over collection type (``.'' vs. ``$\rightarrow$'')"/>
        <details key="text" value=""/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-style"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallInvalid" abstract="true"
        eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="formalParameters" upperBound="-1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actualParameters" upperBound="-1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallInvalidNumberOfParameters"
        eSuperTypes="#//atl_error/OperationCallInvalid #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Invalid number of actual parameters"/>
        <details key="text" value="The number of actual parameters does not match the formal parameters"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallInvalidParameter" eSuperTypes="#//atl_error/OperationCallInvalid #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Invalid actual parameter type"/>
        <details key="text" value="The types of the actual parameters does not match the formal parameters"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blamedParameterNames"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationNotFoundInThisModule" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Operation not found in ThisModule"/>
        <details key="text" value="Operation defined in the transformation scope cannot be found (i.e., invoked with thisModule.operation())."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maybeRule" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeNotFoundInThisModule" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Attribute not found in ThisModule"/>
        <details key="text" value="Attribute defined in the transformation scope cannot be found (i.e., invoked with thisModule.operation())."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureNotFoundInUnionType" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Feature not found in union type"/>
        <details key="text" value="Feature cannot be found in one or more of the possible types of an expression. Only applicable when an expression is deemed have several possible types."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="not-found-in-union"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidOperator" eSuperTypes="#//atl_error/InvalidArgumentProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Invalid operator"/>
        <details key="text" value="Operator not applicable to a certain type."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorSymbol" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidOperand" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/RuntimeError">
      <eAnnotations source="description">
        <details key="name" value="Invalid operand"/>
        <details key="text" value="Operand of the wrong type."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorSymbol" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoContainerForRefImmediateComposite"
        eSuperTypes="#//atl_error/NavigationProblem">
      <eAnnotations source="description">
        <details key="name" value="Object without container"/>
        <details key="text" value="A call to refImmediateComposite() will *always* result in OclUndefined."/>
        <details key="example" value="&#xA;&#x9;&#x9;Given a root class, e.g., MyClassModel, the expression&#xA;&#x9;    aClassModel.refImmediateComposite() will always return null.&#x9;&#xA;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DifferentBranchTypes" eSuperTypes="#//atl_error/NavigationProblem #//atl_error/Warning">
      <eAnnotations source="disabled"/>
      <eAnnotations source="description">
        <details key="name" value="Different branch types"/>
        <details key="text" value="[Disabled] The types of both if branches should be compatible. Perhaps this should be part of ocl compliance checkings..."/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-ocl"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenType" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseType" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingProblem" abstract="true" eSuperTypes="#//atl_error/LocalProblem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolveTempProblem" abstract="true"
        eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssignmentToReadonlyFeature" eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Could not assign a derived featuer"/>
        <details key="text" value="The binding feature has the isDerived flag (i.e., it is a readonly feature)"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingExpectedOneAssignedMany" eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Collection assigned to mono-valued binding"/>
        <details key="text" value="The binding feature is mono-valued but the right part of the binding is a collection"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveBindingButObjectAssigned"
        eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Model element assigned to primitive binding"/>
        <details key="text" value="The binding feature is a primitive type but the right part is a model element"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectBindingButPrimitiveAssigned"
        eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Primitive value assigned to object binding"/>
        <details key="text" value="The binding feature is a reference but the right part is a primitive value"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveBindingInvalidAssignment"
        eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="description">
        <details key="name" value="Incompatible primitive value for primitive binding"/>
        <details key="text" value="The binding feature is primitive but the right part is a non-compatible primitive value"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingResolution" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightType" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//atl_error/ModelElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//atl_error/ModelElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
          eType="#//atl_error/ResolvedRuleInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolvedRuleInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allInvolvedRules" lowerBound="1"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolveTempWithoutRule" eSuperTypes="#//atl_error/ResolveTempProblem">
      <eAnnotations source="description">
        <details key="name" value="No rule to resolve a resolveTemp operation"/>
        <details key="text" value="No rule able to resolve the resolveTemp operation can be found"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="unresolved-resolvedtemp"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolveTempPossiblyUnresolved" eSuperTypes="#//atl_error/ResolveTempProblem #//atl_error/BindingResolution">
      <eAnnotations source="description">
        <details key="name" value="ResolveTemp possibly unresolved"/>
        <details key="text" value="A resolve temp be unresolved if certain conditions hold"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="always-solver"/>
        <details key="path" value="yes"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eAnnotations source="ignorestring">
        <details key="name" value="unresolved-resolvedtemp"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="problematicClasses" lowerBound="1"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="problematicClassesImplicit"
          lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedExpression" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolveTempOutputPatternElementNotFound"
        eSuperTypes="#//atl_error/ResolveTempProblem">
      <eAnnotations source="description">
        <details key="name" value="Undefined output pattern in resolveTemp operation"/>
        <details key="text" value="The given output pattern of the possible matched rules is not defined"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-rules"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
          eType="#//atl_error/ResolvedRuleInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FlattenOverNonNestedCollection" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Flatten over non-nested collection"/>
        <details key="text" value="Example: Sequence {'a', 'b'}->flatten()"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="code" value="401"/>
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-perf"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeSelectFirstForAny" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Change select-first for any"/>
        <details key="text" value="Example: Sequence {'a', 'b'}->select(v | v = 'a')->first()"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-perf"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorOverEmptySequence" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Iterator over empty collection"/>
        <details key="text" value="Example: Sequence { }->select(...)"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidOperatorUsage" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid operator usage"/>
        <details key="text" value="Example: attr.visibility = 'public'"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReadingTargetModel" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Read access to target model"/>
        <details key="text" value="[DISABLE?] False positives when the same meta-model is used as source and target"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WritingSourceModel" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Creation of source elements"/>
        <details key="text" value="Source elements should not appear in the 'to' part of rules'"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LazyRuleWithFilter" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Lazy rule with filter"/>
        <details key="text" value="In practice filters in lazy rules are not evaluated"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidRuleInheritance" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid rule inheritance"/>
        <details key="text" value="Problems with rule inheritance of diverse kind"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1"
          eType="#//atl_error/InvalidRuleInheritanceKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InvalidRuleInheritanceKind">
      <eLiterals name="DIFFERENT_NUMBER_OF_IPE"/>
      <eLiterals name="DIFFERENT_IPE_NAMES" value="1"/>
      <eLiterals name="OTHER" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AmbiguousTargetModelReference" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="disabled"/>
      <eAnnotations source="description">
        <details key="name" value="Ambiguous model reference"/>
        <details key="text" value="[TODO]: Implemented but need to find an example"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="analysis"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoModelFound" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid meta-model name"/>
        <details key="text" value="The specified model is not declared"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-load"/>
        <details key="when" value="trafo-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoEnumLiteral" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Enum literal not found"/>
        <details key="text" value="There is no enum declaration with the given enum literal"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-load"/>
        <details key="when" value="trafo-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WrongType" abstract="true" eSuperTypes="#//atl_error/LocalProblem"/>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorBodyWrongType" eSuperTypes="#//atl_error/WrongType">
      <eAnnotations source="description">
        <details key="name" value="Wrong iterator body type"/>
        <details key="text" value="The inferred type of the iterator body is not compatible with the type expected by the iterator "/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchedRuleWithoutOutputPattern" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Matched rule without output pattern"/>
        <details key="text" value="This should be checked by the parser"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchedRuleFilterNonBoolean" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Matched rule with non-boolean filter"/>
        <details key="text" value="The filter of a matched rule must be boolean"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpectedCollectionInForEach" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Foreach statement expected collection"/>
        <details key="text" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoClassFoundInMetamodel" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid meta-class name"/>
        <details key="text" value="The meta-class name cannot be found in the meta-model"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-load"/>
        <details key="when" value="trafo-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidArgument" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Invalid argument for built-in function"/>
        <details key="text" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionOperationNotFound" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Collection operation not found"/>
        <details key="text" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="none"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorOverNoCollectionType" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Iterator over no collection type"/>
        <details key="text" value=""/>
        <details key="example" value="anObject->select(...)"/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="navigation"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteratorName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractIncoherentVariableDeclaration"
        abstract="true" eSuperTypes="#//atl_error/LocalProblem #//atl_error/OclCompliance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inferred" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declared" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncoherentVariableDeclaration" eSuperTypes="#//atl_error/AbstractIncoherentVariableDeclaration">
      <eAnnotations source="description">
        <details key="name" value="Incoherent variable declaration"/>
        <details key="text" value="The declared and the inferred type are not compatible"/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-style"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncoherentHelperReturnType" eSuperTypes="#//atl_error/AbstractIncoherentVariableDeclaration">
      <eAnnotations source="description">
        <details key="name" value="Incoherent helper return type"/>
        <details key="text" value="The declared and the inferred return type are not compatible"/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-style"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value="OCL spec, tests"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingInplaceInvalid" eSuperTypes="#//atl_error/BindingProblem">
      <eAnnotations source="disabled"/>
      <eAnnotations source="description">
        <details key="name" value="Invalid in-place binding assignment"/>
        <details key="text" value=""/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="yes"/>
        <details key="severity" value="error-target"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="tgt-typing"/>
        <details key="phase" value="analysis"/>
        <details key="source" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightType" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CannotInstantiateAbstractClass" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Abstract class instantiation"/>
        <details key="text" value=""/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="runtime-error"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="typing"/>
        <details key="source" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Metaclass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericLocalProblem" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Generic local problem"/>
        <details key="text" value=""/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="warning-behaviour"/>
        <details key="when" value="model-dep"/>
        <details key="kind" value="src-typing"/>
        <details key="phase" value="typing"/>
        <details key="source" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericKind" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AtlParseError" eSuperTypes="#//atl_error/LocalProblem">
      <eAnnotations source="description">
        <details key="name" value="Parse error"/>
        <details key="text" value=""/>
        <details key="example" value=""/>
      </eAnnotations>
      <eAnnotations source="info">
        <details key="prec" value="static"/>
        <details key="path" value="no"/>
        <details key="severity" value="error-load"/>
        <details key="when" value="always"/>
        <details key="kind" value="trafo-integrity"/>
        <details key="phase" value="parsing"/>
        <details key="source" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericKind" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="atl_recovery" nsURI="http://bento/analysis/atl/analysis/recovery"
      nsPrefix="atl_recovery">
    <eClassifiers xsi:type="ecore:EClass" name="TentativeTypeAssigned" eSuperTypes="#//Recovery">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ide_error" nsURI="http://bento/analysis/atl/analysis/errors/ide"
      nsPrefix="ide_error">
    <eClassifiers xsi:type="ecore:EClass" name="CouldNotLoadMetamodel" eSuperTypes="#//atl_error/LocalProblem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreconditionParseError" eSuperTypes="#//atl_error/LocalProblem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messages" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
