<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atlext" nsURI="http://anatlyzer/atl/ext" nsPrefix="atlext">
  <eAnnotations source="merge">
    <details key="name" value="atlstatic"/>
  </eAnnotations>
  <eSubpackages name="ATL" nsURI="http://anatlyzer/atlext/ATL" nsPrefix="atl_ext_atl">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchedRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutPatternElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Callable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledBy" upperBound="-1"
          eType="#//OCL/PropertyCallExp" eOpposite="#//OCL/PropertyCallExp/staticResolver"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callableParameters" upperBound="-1"
          eType="#//ATL/CallableParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallableParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticType" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paramDeclaration" eType="#//OCL/VariableDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextHelper">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contextType" lowerBound="1"
          eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="polymorphicCalledBy"
          upperBound="-1" eType="#//OCL/PropertyCallExp" eOpposite="#//OCL/PropertyCallExp/dynamicResolvers"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Helper">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasContext" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAttribute" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inferredReturnType" eType="ecore:EClass types.ecore#//Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticReturnType" eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="writtenFeature" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedBy" upperBound="-1"
          eType="#//ATL/RuleResolutionInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuleResolutionInfo">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1"
          eType="#//ATL/MatchedRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allInvolvedRules" lowerBound="1"
          upperBound="-1" eType="#//ATL/MatchedRule"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="OCL" nsURI="http://anatlyzer/atl/ext/OCL" nsPrefix="atl_ext_ocl">
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inferredType" eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//OCL/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticType" eType="ecore:EClass types.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclExpression" eSuperTypes="#//OCL/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitlyCasted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receptorType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStaticCall" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staticResolver" lowerBound="1"
          eType="#//ATL/Callable" eOpposite="#//ATL/Callable/calledBy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicResolvers" upperBound="-1"
          eType="#//ATL/ContextHelper" eOpposite="#//ATL/ContextHelper/polymorphicCalledBy"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolveTempResolvedBy"
          upperBound="-1" eType="#//OCL/ResolveTempResolution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResolveTempResolution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1"
          eType="#//ATL/MatchedRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="#//ATL/OutPatternElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaBody" eSuperTypes="#//OCL/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="GetAppliedStereotypesBody" eSuperTypes="#//OCL/JavaBody"/>
  </eSubpackages>
  <eSubpackages name="PrimitiveTypes" nsURI="http://anatlyzer/atl/ext/PrimitiveTypes"
      nsPrefix="atl_ext_ptypes"/>
</ecore:EPackage>
