<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="impact" nsURI="http://anatlyzer/atl/impact" nsPrefix="atl_impact">
  <eClassifiers xsi:type="ecore:EClass" name="ChangeImpact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changes" upperBound="-1"
        eType="#//Change" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Change" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Create" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallableChange" abstract="true" eSuperTypes="#//Change">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callable" lowerBound="1"
        eType="ecore:EClass generated/merged.ecore#//ATL/Callable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invalidated" upperBound="-1"
        eType="ecore:EClass generated/merged.ecore#//OCL/PropertyCallExp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextCallableChange" eSuperTypes="#//CallableChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleCallableChange" eSuperTypes="#//CallableChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMatchedRule" eSuperTypes="#//Change #//Create">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="ecore:EClass generated/merged.ecore#//ATL/MatchedRule"/>
  </eClassifiers>
</ecore:EPackage>
