/**
 *
 * $Id$
 */
package anatlyzer.atl.errors.atl_error.validation;

import anatlyzer.atl.errors.atl_error.ModelElement;
import anatlyzer.atl.errors.atl_error.ResolvedRuleInfo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link anatlyzer.atl.errors.atl_error.BindingResolution}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BindingResolutionValidator {
	boolean validate();

	boolean validateRightType(EClass value);
	boolean validateTargetType(EClass value);
	boolean validateRight(ModelElement value);
	boolean validateLeft(ModelElement value);
	boolean validateRules(EList<ResolvedRuleInfo> value);
}
