/**
 *
 * $Id$
 */
package anatlyzer.atl.errors.atl_error.validation;

import anatlyzer.atl.types.Metaclass;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link anatlyzer.atl.errors.atl_error.ConflictingRuleSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConflictingRuleSetValidator {
	boolean validate();

	boolean validateType(Metaclass value);
	boolean validateRules(EList<EObject> value);
	boolean validateAnalyserInfo(Object value);
}
