/**
 *
 * $Id$
 */
package anatlyzer.atl.errors.atl_error.validation;

import anatlyzer.atl.errors.Recovery;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link anatlyzer.atl.errors.atl_error.LocalProblem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LocalProblemValidator {
	boolean validate();

	boolean validateLocation(String value);
	boolean validateFileLocation(String value);
	boolean validateElement(EObject value);
	boolean validateDisplayedElement(EObject value);
	boolean validateMissing(Object value);
	boolean validateRecovery(Recovery value);
}
