/**
 *
 * $Id$
 */
package anatlyzer.atl.errors.atl_error.validation;

import anatlyzer.atl.types.Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link anatlyzer.atl.errors.atl_error.OperationCallInvalid}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationCallInvalidValidator {
	boolean validate();

	boolean validateOperationName(String value);
	boolean validateType(Type value);
	boolean validateClassName(String value);
	boolean validateMetamodelName(String value);
	boolean validateFormalParameters(EList<Type> value);
	boolean validateActualParameters(EList<Type> value);
}
