/**
 *
 * $Id$
 */
package anatlyzer.atl.errors.validation;

import anatlyzer.atl.errors.BatchAnalysis;
import anatlyzer.atl.errors.Problem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link anatlyzer.atl.errors.AnalysisResult}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnalysisResultValidator {
	boolean validate();

	boolean validateProblems(EList<Problem> value);
	boolean validateBatchAnalysis(EList<BatchAnalysis> value);
}
