<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java" nsURI="java" nsPrefix="java">
  <eAnnotations source="java"/>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchCase" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationStatement" eSuperTypes="//Statement //AbstractVariablesContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationExpression" eSuperTypes="//Expression //AbstractVariablesContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" abstract="true" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassDeclaration" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyDeclarations" upperBound="-1" eType="//BodyDeclaration" containment="true" eOpposite="//BodyDeclaration/anonymousClassDeclarationOwner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatchClause" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" lowerBound="1" eType="//SingleVariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeInt" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1" eType="//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orphanTypes" upperBound="-1" eType="//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archives" upperBound="-1" eType="//Archive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnits" upperBound="-1" eType="//CompilationUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BodyDeclaration" abstract="true" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractTypeDeclaration" eType="//AbstractTypeDeclaration" eOpposite="//AbstractTypeDeclaration/bodyDeclarations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousClassDeclarationOwner" eType="//AnonymousClassDeclaration" eOpposite="//AnonymousClassDeclaration/bodyDeclarations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifier" eType="//Modifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragment" eSuperTypes="//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variablesContainer" eType="//AbstractVariablesContainer" eOpposite="//AbstractVariablesContainer/fragments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorDeclaration" eSuperTypes="//AbstractMethodDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="//TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfixExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedOperands" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="//InfixExpressionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeDeclaration" eSuperTypes="//AbstractTypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializers" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updaters" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConstantDeclaration" eSuperTypes="//BodyDeclaration //VariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeChar" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodDeclaration" abstract="true" eSuperTypes="//BodyDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//SingleVariableDeclaration" containment="true" eOpposite="//SingleVariableDeclaration/methodDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1" eType="//TypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thrownExceptions" upperBound="-1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParenthesizedExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1" eType="//AbstractTypeDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackages" upperBound="-1" eType="//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeMemberDeclaration" eSuperTypes="//BodyDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassInstanceCreation" eSuperTypes="//Expression //AbstractMethodInvocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousClassDeclaration" eType="//AnonymousClassDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayCreation" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="//ArrayInitializer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedItemAccess" eSuperTypes="//Expression //NamespaceAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="//UnresolvedItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftHandSide" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightHandSide" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="//AssignmentKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssertStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatement" lowerBound="1" eType="//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalCompilationUnit" eType="//CompilationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalClassFile" eType="//ClassFile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1" eType="//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedTypeDeclaration" eSuperTypes="//AbstractTypeDeclaration //UnresolvedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperConstructorInvocation" eSuperTypes="//Statement //AbstractMethodInvocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" eSuperTypes="//BodyDeclaration //AbstractVariablesContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnhancedForStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1" eType="//SingleVariableDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinueStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="//LabeledStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagElement" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeQualifiedExpression" abstract="true" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteral" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperFieldAccess" eSuperTypes="//AbstractTypeQualifiedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="//SingleVariableAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeByte" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensions" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeDouble" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="//BodyDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="//AbstractTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumConstants" upperBound="-1" eType="//EnumConstantDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValuePair" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="//AnnotationTypeMemberDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifier" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1" eType="//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritance" lowerBound="1" eType="//InheritanceKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildCardType" eSuperTypes="//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bound" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedType" eSuperTypes="//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeLong" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclarationStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" eType="//AbstractTypeDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TryStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" upperBound="-1" eType="//CatchClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finally" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledStatement" eSuperTypes="//NamedElement //Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportDeclaration" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement" lowerBound="1" eType="//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeDeclaration" abstract="true" eSuperTypes="//BodyDeclaration //Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superInterfaces" upperBound="-1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentsAfterBody" upperBound="-1" eType="//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyDeclarations" upperBound="-1" eType="//BodyDeclaration" containment="true" eOpposite="//BodyDeclaration/abstractTypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commentsBeforeBody" upperBound="-1" eType="//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostfixExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="//PostfixExpressionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterLiteral" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="escapedValue" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodDeclaration" eSuperTypes="//AbstractMethodDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="escapedValue" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorInvocation" eSuperTypes="//Statement //AbstractMethodInvocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Archive" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalFilePath" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedItem" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation" eSuperTypes="//Expression //AbstractMethodInvocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodInvocation" abstract="true" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1" eType="//AbstractMethodDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThrowStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeBoolean" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="//SingleVariableAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1" eType="//AbstractTypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1" eType="//ImportDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalFilePath" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="//AnnotationMemberValuePair" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceofExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractVariablesContainer" abstract="true" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1" eType="//VariableDeclarationFragment" containment="true" eOpposite="//VariableDeclarationFragment/variablesContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="//TypeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeShort" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializer" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenValue" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAccess" eSuperTypes="//Expression //NamespaceAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="//LabeledStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayLengthAccess" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeFloat" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceDeclaration" eSuperTypes="//TypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodRefParameter" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleVariableAccess" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1" eType="//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="//PrefixExpressionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperMethodInvocation" eSuperTypes="//AbstractTypeQualifiedExpression //AbstractMethodInvocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleVariableDeclaration" eSuperTypes="//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodDeclaration" eType="//AbstractMethodDeclaration" eOpposite="//AbstractMethodDeclaration/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//TypeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifier" eType="//Modifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodRef" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassFile" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayAccess" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeVoid" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThisExpression" eSuperTypes="//AbstractTypeQualifiedExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" abstract="true" eSuperTypes="//AbstractTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1" eType="//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberRef" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizedStatement" eSuperTypes="//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssignmentKind">
    <eLiterals name="ASSIGN" value="1" literal="="/>
    <eLiterals name="PLUS_ASSIGN" value="2" literal="+="/>
    <eLiterals name="MINUS_ASSIGN" value="3" literal="-="/>
    <eLiterals name="TIMES_ASSIGN" value="4" literal="*="/>
    <eLiterals name="DIVIDE_ASSIGN" value="5" literal="/="/>
    <eLiterals name="BIT_AND_ASSIGN" value="6" literal="&amp;="/>
    <eLiterals name="BIT_OR_ASSIGN" value="7" literal="|="/>
    <eLiterals name="BIT_XOR_ASSIGN" value="8" literal="^="/>
    <eLiterals name="REMAINDER_ASSIGN" value="9" literal="%="/>
    <eLiterals name="LEFT_SHIFT_ASSIGN" value="10" literal="&lt;&lt;="/>
    <eLiterals name="RIGHT_SHIFT_SIGNED_ASSIGN" value="11" literal=">>="/>
    <eLiterals name="RIGHT_SHIFT_UNSIGNED_ASSIGN" value="12" literal=">>>="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="none" value="1"/>
    <eLiterals name="public" value="2"/>
    <eLiterals name="private" value="3"/>
    <eLiterals name="protected" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InheritanceKind">
    <eLiterals name="none" value="1"/>
    <eLiterals name="abstract" value="2"/>
    <eLiterals name="final" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrefixExpressionKind">
    <eLiterals name="INCREMENT" value="1" literal="++"/>
    <eLiterals name="DECREMENT" value="2" literal="--"/>
    <eLiterals name="PLUS" value="3" literal="+"/>
    <eLiterals name="MINUS" value="4" literal="-"/>
    <eLiterals name="COMPLEMENT" value="5" literal="~"/>
    <eLiterals name="NOT" value="6" literal="!"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PostfixExpressionKind">
    <eLiterals name="INCREMENT" value="1" literal="++"/>
    <eLiterals name="DECREMENT" value="2" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InfixExpressionKind">
    <eLiterals name="TIMES" value="1" literal="*"/>
    <eLiterals name="DIVIDE" value="2" literal="/"/>
    <eLiterals name="REMAINDER" value="3" literal="%"/>
    <eLiterals name="PLUS" value="4" literal="+"/>
    <eLiterals name="MINUS" value="5" literal="-"/>
    <eLiterals name="LEFT_SHIFT" value="6" literal="&lt;&lt;"/>
    <eLiterals name="RIGHT_SHIFT_SIGNED" value="7" literal=">>"/>
    <eLiterals name="RIGHT_SHIFT_UNSIGNED" value="8" literal=">>>"/>
    <eLiterals name="LESS" value="9" literal="&lt;"/>
    <eLiterals name="GREATER" value="10" literal=">"/>
    <eLiterals name="LESS_EQUALS" value="11" literal="&lt;="/>
    <eLiterals name="GREATER_EQUALS" value="12" literal=">="/>
    <eLiterals name="EQUALS" value="13" literal="=="/>
    <eLiterals name="NOT_EQUALS" value="14" literal="!="/>
    <eLiterals name="XOR" value="15" literal="^"/>
    <eLiterals name="AND" value="16" literal="&amp;"/>
    <eLiterals name="OR" value="17" literal="|"/>
    <eLiterals name="CONDITIONAL_AND" value="18" literal="&amp;&amp;"/>
    <eLiterals name="CONDITIONAL_OR" value="19" literal="||"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceAccess" abstract="true" eSuperTypes="//ASTNode"/>
</ecore:EPackage>
