<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="error1" nsURI="error1" nsPrefix="prefix1">
  <eAnnotations source="Binding may be resolved by rule with invalid target type (src : NamedElement). 268:4-268:33&#xA;&#x9;CompilationUnitToSourceFile 767:1-774:2&#xA;&#x9;LabeledStatementToActionElement 1360:1-1368:2&#xA;&#x9;AnnotationMemberValuePairToAttribute 1710:1-1737:2&#xA;&#x9;ArchiveToBinaryFile 776:1-782:2&#xA;"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValuePair" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConstantDeclaration" eSuperTypes="//BodyDeclaration //VariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodDeclaration" abstract="true" eSuperTypes="//BodyDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1" eType="//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeChar" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractVariablesContainer" abstract="true" eSuperTypes="//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1" eType="//VariableDeclarationFragment" containment="true" eOpposite="//VariableDeclarationFragment/variablesContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildCardType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeMemberDeclaration" eSuperTypes="//BodyDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeShort" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeLong" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledStatement" eSuperTypes="//NamedElement //Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeFloat" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceDeclaration" eSuperTypes="//TypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" eSuperTypes="//BodyDeclaration //AbstractVariablesContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeInt" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleVariableDeclaration" eSuperTypes="//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodDeclaration" eType="//AbstractMethodDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archive" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BodyDeclaration" abstract="true" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragment" eSuperTypes="//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variablesContainer" eType="//AbstractVariablesContainer" eOpposite="//AbstractVariablesContainer/fragments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="//TypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeByte" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeDouble" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeVoid" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeBoolean" eSuperTypes="//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="//BodyDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeDeclaration" eSuperTypes="//AbstractTypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThisModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="//AbstractTypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" abstract="true" eSuperTypes="//AbstractTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1" eType="//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeDeclaration" abstract="true" eSuperTypes="//BodyDeclaration //Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyDeclarations" upperBound="-1" eType="//BodyDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTNode" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" abstract="true" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="//ASTNode"/>
</ecore:EPackage>
