<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="atlstatic" nsURI="http://anatlyzer/atlstatic" nsPrefix="atlstatic">
  <eSubpackages name="ATL" nsURI="http://anatlyzer/atlstatic/ATL" nsPrefix="atl">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
          unique="false" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false"
          upperBound="-1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false"
          upperBound="-1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" ordered="false"
          upperBound="-1" eType="#//ATL/LibraryRef" containment="true" eOpposite="#//ATL/LibraryRef/unit"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//ATL/Unit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="helpers" upperBound="-1"
          eType="#//ATL/Helper" containment="true" eOpposite="#//ATL/Helper/library"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//ATL/Unit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="helpers" upperBound="-1"
          eType="#//ATL/Helper" containment="true" eOpposite="#//ATL/Helper/query"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//ATL/Unit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRefining" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inModels" lowerBound="1"
          upperBound="-1" eType="#//OCL/OclModel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outModels" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//OCL/OclModel" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//ATL/ModuleElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleElement" abstract="true" eSuperTypes="#//ATL/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Helper" eSuperTypes="#//ATL/ModuleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="query" ordered="false"
          eType="#//ATL/Query" eOpposite="#//ATL/Query/helpers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="library" ordered="false"
          eType="#//ATL/Library" eOpposite="#//ATL/Library/helpers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false"
          lowerBound="1" eType="#//OCL/OclFeatureDefinition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true" eSuperTypes="#//ATL/ModuleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outPattern" ordered="false"
          eType="#//ATL/OutPattern" containment="true" eOpposite="#//ATL/OutPattern/rule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionBlock" ordered="false"
          eType="#//ATL/ActionBlock" containment="true" eOpposite="#//ATL/ActionBlock/rule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//ATL/RuleVariableDeclaration" containment="true" eOpposite="#//ATL/RuleVariableDeclaration/rule"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchedRule" eSuperTypes="#//ATL/Rule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inPattern" ordered="false"
          eType="#//ATL/InPattern" containment="true" eOpposite="#//ATL/InPattern/rule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
          upperBound="-1" eType="#//ATL/MatchedRule" eOpposite="#//ATL/MatchedRule/superRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superRule" ordered="false"
          eType="#//ATL/MatchedRule" eOpposite="#//ATL/MatchedRule/children"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRefining" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNoDefault" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LazyMatchedRule" eSuperTypes="#//ATL/MatchedRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalledRule" eSuperTypes="#//ATL/Rule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
          upperBound="-1" eType="#//OCL/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEntrypoint" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEndpoint" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InPattern" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//ATL/InPatternElement" containment="true"
          eOpposite="#//ATL/InPatternElement/inPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" ordered="false"
          lowerBound="1" eType="#//ATL/MatchedRule" eOpposite="#//ATL/MatchedRule/inPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
          eType="#//OCL/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutPattern" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" ordered="false"
          lowerBound="1" eType="#//ATL/Rule" eOpposite="#//ATL/Rule/outPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
          upperBound="-1" eType="#//ATL/OutPatternElement" containment="true" eOpposite="#//ATL/OutPatternElement/outPattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatternElement" abstract="true" eSuperTypes="#//OCL/VariableDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="InPatternElement" abstract="true"
        eSuperTypes="#//ATL/PatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" ordered="false"
          lowerBound="1" eType="#//ATL/OutPatternElement" eOpposite="#//ATL/OutPatternElement/sourceElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inPattern" ordered="false"
          lowerBound="1" eType="#//ATL/InPattern" eOpposite="#//ATL/InPattern/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="models" ordered="false"
          upperBound="-1" eType="#//OCL/OclModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleInPatternElement" eSuperTypes="#//ATL/InPatternElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutPatternElement" abstract="true"
        eSuperTypes="#//ATL/PatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outPattern" ordered="false"
          lowerBound="1" eType="#//ATL/OutPattern" eOpposite="#//ATL/OutPattern/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" ordered="false"
          eType="#//ATL/InPatternElement" eOpposite="#//ATL/InPatternElement/mapsTo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//ATL/Binding" containment="true" eOpposite="#//ATL/Binding/outPatternElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
          eType="#//OCL/OclModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleOutPatternElement" eSuperTypes="#//ATL/OutPatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reverseBindings" upperBound="-1"
          eType="#//OCL/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForEachOutPatternElement" eSuperTypes="#//ATL/OutPatternElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collection" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" ordered="false"
          lowerBound="1" eType="#//OCL/Iterator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outPatternElement" ordered="false"
          lowerBound="1" eType="#//ATL/OutPatternElement" eOpposite="#//ATL/OutPatternElement/bindings"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAssignment" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuleVariableDeclaration" eSuperTypes="#//OCL/VariableDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" ordered="false"
          lowerBound="1" eType="#//ATL/Rule" eOpposite="#//ATL/Rule/variables"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LibraryRef" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" ordered="false"
          lowerBound="1" eType="#//ATL/Unit" eOpposite="#//ATL/Unit/libraries"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionBlock" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" ordered="false"
          lowerBound="1" eType="#//ATL/Rule" eOpposite="#//ATL/Rule/actionBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//ATL/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//ATL/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionStat" eSuperTypes="#//ATL/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingStat" eSuperTypes="#//ATL/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAssignment" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStat" eSuperTypes="#//ATL/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatements" upperBound="-1"
          eType="#//ATL/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatements" upperBound="-1"
          eType="#//ATL/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForStat" eSuperTypes="#//ATL/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" ordered="false"
          lowerBound="1" eType="#//OCL/Iterator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collection" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//ATL/Statement" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="OCL" nsURI="http://anatlyzer/atlstatic/OCL" nsPrefix="ocl">
    <eClassifiers xsi:type="ecore:EClass" name="OclExpression" abstract="true" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false"
          eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/oclExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifExp3" ordered="false"
          eType="#//OCL/IfExp" eOpposite="#//OCL/IfExp/elseExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliedProperty" ordered="false"
          eType="#//OCL/PropertyCallExp" eOpposite="#//OCL/PropertyCallExp/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collection" ordered="false"
          eType="#//OCL/CollectionExp" eOpposite="#//OCL/CollectionExp/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="letExp" ordered="false"
          eType="#//OCL/LetExp" eOpposite="#//OCL/LetExp/in_"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopExp" ordered="false"
          eType="#//OCL/LoopExp" eOpposite="#//OCL/LoopExp/body"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentOperation" ordered="false"
          eType="#//OCL/OperationCallExp" eOpposite="#//OCL/OperationCallExp/arguments"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializedVariable"
          ordered="false" eType="#//OCL/VariableDeclaration" eOpposite="#//OCL/VariableDeclaration/initExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifExp2" ordered="false"
          eType="#//OCL/IfExp" eOpposite="#//OCL/IfExp/thenExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" ordered="false"
          eType="#//OCL/Operation" eOpposite="#//OCL/Operation/body"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifExp1" ordered="false"
          eType="#//OCL/IfExp" eOpposite="#//OCL/IfExp/condition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningAttribute" ordered="false"
          eType="#//OCL/Attribute" eOpposite="#//OCL/Attribute/initExpression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" ordered="false"
          lowerBound="1" eType="#//OCL/VariableDeclaration" eOpposite="#//OCL/VariableDeclaration/variableExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperExp" eSuperTypes="#//OCL/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveExp" abstract="true" eSuperTypes="#//OCL/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringExp" eSuperTypes="#//OCL/PrimitiveExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringSymbol" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExp" eSuperTypes="#//OCL/PrimitiveExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanSymbol" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericExp" abstract="true" eSuperTypes="#//OCL/PrimitiveExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealExp" eSuperTypes="#//OCL/NumericExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="realSymbol" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerExp" eSuperTypes="#//OCL/NumericExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerSymbol" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionExp" abstract="true" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/collection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BagExp" eSuperTypes="#//OCL/CollectionExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSetExp" eSuperTypes="#//OCL/CollectionExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceExp" eSuperTypes="#//OCL/CollectionExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="SetExp" eSuperTypes="#//OCL/CollectionExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="TupleExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tuplePart" upperBound="-1"
          eType="#//OCL/TuplePart" containment="true" eOpposite="#//OCL/TuplePart/tuple"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TuplePart" eSuperTypes="#//OCL/VariableDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" ordered="false"
          lowerBound="1" eType="#//OCL/TupleExp" eOpposite="#//OCL/TupleExp/tuplePart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//OCL/MapElement" containment="true" eOpposite="#//OCL/MapElement/map"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapElement" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="map" ordered="false"
          lowerBound="1" eType="#//OCL/MapExp" eOpposite="#//OCL/MapExp/elements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclUndefinedExp" eSuperTypes="#//OCL/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExp" abstract="true" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/appliedProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationOrAttributeCallExp" eSuperTypes="#//OCL/PropertyCallExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallExp" eSuperTypes="#//OCL/PropertyCallExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/parentOperation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperatorCallExp" eSuperTypes="#//OCL/OperationCallExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionOperationCallExp" eSuperTypes="#//OCL/OperationCallExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="LoopExp" abstract="true" eSuperTypes="#//OCL/PropertyCallExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/loopExp"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterators" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//OCL/Iterator" containment="true"
          eOpposite="#//OCL/Iterator/loopExpr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IterateExp" eSuperTypes="#//OCL/LoopExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" ordered="false"
          lowerBound="1" eType="#//OCL/VariableDeclaration" containment="true" eOpposite="#//OCL/VariableDeclaration/baseExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorExp" eSuperTypes="#//OCL/LoopExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LetExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
          lowerBound="1" eType="#//OCL/VariableDeclaration" containment="true" eOpposite="#//OCL/VariableDeclaration/letExp"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in_" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/letExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfExp" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/ifExp2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/ifExp1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/ifExp3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
          eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false"
          eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/variableDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" ordered="false"
          eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/initializedVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="letExp" ordered="false"
          eType="#//OCL/LetExp" eOpposite="#//OCL/LetExp/variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseExp" ordered="false"
          eType="#//OCL/IterateExp" eOpposite="#//OCL/IterateExp/result"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableExp" ordered="false"
          upperBound="-1" eType="#//OCL/VariableExp" eOpposite="#//OCL/VariableExp/referredVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Iterator" eSuperTypes="#//OCL/VariableDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopExpr" ordered="false"
          eType="#//OCL/LoopExp" eOpposite="#//OCL/LoopExp/iterators"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//OCL/VariableDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//OCL/OclType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/collectionTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclType" eSuperTypes="#//OCL/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" ordered="false"
          eType="#//OCL/OclContextDefinition" eOpposite="#//OCL/OclContextDefinition/context_"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oclExpression" ordered="false"
          eType="#//OCL/OclExpression" eOpposite="#//OCL/OclExpression/type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
          eType="#//OCL/Operation" eOpposite="#//OCL/Operation/returnType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapType2" ordered="false"
          eType="#//OCL/MapType" eOpposite="#//OCL/MapType/valueType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
          eType="#//OCL/Attribute" eOpposite="#//OCL/Attribute/type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapType" ordered="false"
          eType="#//OCL/MapType" eOpposite="#//OCL/MapType/keyType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionTypes" ordered="false"
          eType="#//OCL/CollectionType" eOpposite="#//OCL/CollectionType/elementType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tupleTypeAttribute" ordered="false"
          eType="#//OCL/TupleTypeAttribute" eOpposite="#//OCL/TupleTypeAttribute/type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration"
          ordered="false" eType="#//OCL/VariableDeclaration" eOpposite="#//OCL/VariableDeclaration/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true" eSuperTypes="#//OCL/OclType"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//OCL/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//OCL/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="NumericType" abstract="true" eSuperTypes="#//OCL/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//OCL/NumericType"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//OCL/NumericType"/>
    <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="#//OCL/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType" eSuperTypes="#//OCL/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="#//OCL/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//OCL/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclAnyType" eSuperTypes="#//OCL/OclType"/>
    <eClassifiers xsi:type="ecore:EClass" name="TupleType" eSuperTypes="#//OCL/OclType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//OCL/TupleTypeAttribute" containment="true" eOpposite="#//OCL/TupleTypeAttribute/tupleType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleTypeAttribute" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/tupleTypeAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tupleType" ordered="false"
          lowerBound="1" eType="#//OCL/TupleType" eOpposite="#//OCL/TupleType/attributes"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclModelElement" eSuperTypes="#//OCL/OclType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
          lowerBound="1" eType="#//OCL/OclModel" eOpposite="#//OCL/OclModel/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapType" eSuperTypes="#//OCL/OclType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/mapType2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/mapType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclFeatureDefinition" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
          lowerBound="1" eType="#//OCL/OclFeature" containment="true" eOpposite="#//OCL/OclFeature/definition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_" ordered="false"
          eType="#//OCL/OclContextDefinition" containment="true" eOpposite="#//OCL/OclContextDefinition/definition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclContextDefinition" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false"
          lowerBound="1" eType="#//OCL/OclFeatureDefinition" eOpposite="#//OCL/OclFeatureDefinition/context_"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context_" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/definitions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclFeature" abstract="true" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false"
          eType="#//OCL/OclFeatureDefinition" eOpposite="#//OCL/OclFeatureDefinition/feature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//OCL/OclFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/owningAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/attribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//OCL/OclFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//OCL/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" ordered="false"
          lowerBound="1" eType="#//OCL/OclType" containment="true" eOpposite="#//OCL/OclType/operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          lowerBound="1" eType="#//OCL/OclExpression" containment="true" eOpposite="#//OCL/OclExpression/owningOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclModel" eSuperTypes="#//ATL/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" ordered="false"
          lowerBound="1" eType="#//OCL/OclModel" eOpposite="#//OCL/OclModel/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
          upperBound="-1" eType="#//OCL/OclModelElement" eOpposite="#//OCL/OclModelElement/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
          upperBound="-1" eType="#//OCL/OclModel" eOpposite="#//OCL/OclModel/metamodel"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="PrimitiveTypes" nsURI="http://anatlyzer/atlstatic/ATL-PrimitiveTypes"
      nsPrefix="ptypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  </eSubpackages>
</ecore:EPackage>
